services:
  users:
    build:
      context: ../services/users
      dockerfile: Dockerfile
    image: users-service:dev
    container_name: users-service
    ports:
      - "8000:8000"
    restart: unless-stopped
  orders:
    build:
      context: ../services/orders
      dockerfile: Dockerfile
    image: orders-service:dev
    container_name: orders-service
    ports:
      - "8001:8001"
    restart: unless-stopped

  inventory:
    build:
      context: ../services/inventory
      dockerfile: Dockerfile
    image: inventory-service:dev
    container_name: inventory-service
    ports:
      - "8002:8002"
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:v2.54.1
    container_name: prometheus
    volumes:
      - ./observability/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    restart: unless-stopped

  grafana:
    image: grafana/grafana:11.1.4
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    restart: unless-stopped