services:
  users:
    build:
      context: ../services/users
      dockerfile: Dockerfile
    image: users-service:dev
    container_name: users-service
    ports:
      - "8000:8000"
    restart: unless-stopped
  orders:
    build:
      context: ../services/orders
      dockerfile: Dockerfile
    image: orders-service:dev
    container_name: orders-service
    ports:
      - "8001:8001"
    restart: unless-stopped